app/models.py
from app.db import db
from datetime import date


class Author(db.Model):
    __tablename__ = "authors"
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(50))
    birth_date = db.Column(db.Date)
    date_of_death = db.Column(db.Date)

    def __repr__(self):
        return (
            f"<Author(id={self.id}',"
            f"name='{self.name}', "
            f"birth_date='{self.birth_date}', "
            f"date_of_death='{self.date_of_death}')>"
        )

    def __str__(self):
        if self.date_of_death is None:
            return f"{self.name} was born {self.birth_date}"
        return (
            f"{self.name} was born {self.birth_date} "
            f"and died {self.date_of_death}"  # noqa E501
        )


class Book(db.Model):
    __tablename__ = "books"
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    isbn = db.Column(db.String(13))
    title = db.Column(db.String(100))
    publication_year = db.Column(db.Integer)
    author_id = db.Column(db.Integer, db.ForeignKey("authors.id"))


# with app.app_context():
#     db.create_all()


# create ORM classes here
# with app.app_context():
#     db.create_all()

new_author = Author(
    name="J.K. Rowling", birth_date=date(1965, 7, 31), date_of_death=None
)

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField
from wtforms.fields.datetime import DateField
from wtforms.fields.numeric import IntegerField
from wtforms.validators import DataRequired, Optional, Length, NumberRange


class AuthorForm(FlaskForm):
    name = StringField("Author's Name", validators=[DataRequired()])
    birth_date = DateField(
        "Author's Birth Date", validators=[DataRequired()], format="%Y-%m-%d"
    )
    date_of_death = DateField(
        "Author's Death Date", validators=[Optional()], format="%Y-%m-%d"
    )
    submit = SubmitField("Add Author")


class BookForm(FlaskForm):
    author = SelectField("Author", choices=[], validators=[DataRequired()])

    isbn = StringField(
        "ISBN Number",
        validators=[
            DataRequired(),
            Length(
                min=10,
                max=13,
                message="ISBN must be between 10 and 13 characters",  # noqa E501
            ),  # noqa E501
        ],
    )
    title = StringField("Title", validators=[DataRequired()])
    publication_year = IntegerField(
        "Publication Year",
        validators=[
            DataRequired(),
            NumberRange(
                min=1000, max=2025, message="Year must be a 4-digit number"
            ),  # noqa E501
        ],
    )
    submit = SubmitField("Add Book")


class SortForm(FlaskForm):
    sorting_criteria = SelectField(
        "Sort by",
        choices=[("book", "Book Title"), ("author", "Author Name")],
        validators=[DataRequired()],
    )
    sorting_direction = SelectField(
        "Sort Direction",
        choices=[("asc", "Ascending"), ("desc", "Descending")],
        validators=[DataRequired()],
    )
    submit = SubmitField("Sort Inventory")


class SearchForm(FlaskForm):
    item = SelectField(
        "Search by", choices=[("author", "Author"), ("book", "Book")]
    )  # noqa E501
    search = StringField("Search", validators=[DataRequired()])
    submit = SubmitField("Search")


class DeleteBookForm(FlaskForm):
    search = StringField("Search", validators=[DataRequired()])
    submit = SubmitField("Search")


class DeleteAuthorForm(FlaskForm):
    search = StringField("Search", validators=[DataRequired()])
    submit = SubmitField("Search")

app/__init__.py
from flask import Flask
from app.logger import setup_logger
from app.views import main
from pathlib import Path
from app.db import db


from config import config


logger = setup_logger(__name__)
template_path = Path(__file__).parent / "templates"


def create_app(config_name):
    app = Flask(__name__, template_folder=template_path)
    app.config.from_object(config[config_name])
    db.init_app(app)
    logger.info("App created using '%s' config %s", config_name, template_path)

    app.register_blueprint(main)
    return app

app/views.py
from flask import Blueprint, redirect, url_for, render_template, flash, request

from app.forms import (
    AuthorForm,
    BookForm,
    SortForm,
    SearchForm,
    DeleteBookForm,
)  # noqa E501
from app.models import Author
from app.services import DBLogic as dbl
from app.logger import setup_logger


logger = setup_logger(__name__)

main = Blueprint("main", __name__)


@main.before_request
def before_request():
    ip_address = request.remote_addr
    logger.info(f"Incoming request from {ip_address}")


@main.route("/", methods=["POST", "GET"])
def index():
    form = SortForm()
    results = dbl.get_books()
    if form.validate_on_submit():
        sorting_criteria = form.sorting_criteria.data
        sorting_direction = form.sorting_direction.data
        results = dbl.sort_inventory(sorting_criteria, sorting_direction)
        return redirect(url_for("main.index"))
    return render_template("home.html", results=results, form=form)


@main.route("/add_author", methods=["GET", "POST"])
def add_author():
    form = AuthorForm()
    if form.validate_on_submit():
        name = form.name.data
        birth_date = form.birth_date.data
        date_of_death = form.date_of_death.data
        response = dbl.add_author(name, birth_date, date_of_death)
        flash(f"Author {response.name} added to the database")
        return redirect(url_for("main.index"))
    return render_template("add_author.html", form=form)


@main.route("/add_book", methods=["GET", "POST"])
def add_book():
    form = BookForm()
    authors = Author.query.all()
    form.author.choices = [
        (author.id, f"{author.name} ({author.birth_date})")
        for author in authors  # noqa E501
    ]
    if form.validate_on_submit():
        isbn = form.isbn.data
        title = form.title.data
        publication_year = form.publication_year.data
        author_id = form.author.data
        response = dbl.add_book(isbn, title, publication_year, author_id)
        flash(f"Book {response.title} added to the database")
        return redirect(url_for("main.index"))
    return render_template("add_book.html", form=form)


@main.route("/search", methods=["GET", "POST"])
def search():
    form = SearchForm()
    results = []
    if form.validate_on_submit():
        item = form.item.data
        search_pattern = form.search.data
        results = dbl.search_inventory(item, search_pattern)
        return redirect(url_for("main.search"))
    return render_template("search.html", form=form, results=results)


@main.route("/delete_book", methods=["GET", "POST"])
def delete_book():
    form = DeleteBookForm()
    if form.validate_on_submit():
        search_pattern = form.search.data
        result = dbl.search_inventory(item="book", search=search_pattern)
        book, author = result[0]
        book_title = book.title
        if not result:
            flash(f"Book {book_title} not found in the database")
            return redirect(url_for("main.delete_book"))
        else:
            dbl.delete_book(book_title)
            flash(f"Book {book_title.title} deleted from the database")
        return redirect(url_for("main.index"))
    return render_template("delete_book.html", form=form)

app/templates/add_author.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Add Author</title>
    <style>
      .error {
        color: red;
      }
    </style>
  </head>
  <body>
  {% include 'navbar.html' %}
    <h1>Add Author</h1>
    <form method="POST" action="{{ url_for('main.add_author') }}">
      {{ form.hidden_tag() }}

      <p>
        {{ form.name.label }}<br>
        {{ form.name(size=30) }}
        {% for error in form.name.errors %}
          <span class="error">{{ error }}</span>
        {% endfor %}
      </p>

      <p>
        {{ form.birth_date.label }}<br>
        {{ form.birth_date() }}
        {% for error in form.birth_date.errors %}
          <span class="error">{{ error }}</span>
        {% endfor %}
      </p>

      <p>
        {{ form.date_of_death.label }}<br>
        {{ form.date_of_death() }}
        {% for error in form.date_of_death.errors %}
          <span class="error">{{ error }}</span>
        {% endfor %}
      </p>

      <p>
        {{ form.submit() }}
      </p>
    </form>
  </body>
</html>

app/templates/add_book.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <title>Add Book</title>
  </head>
  <body>
  {% include 'navbar.html' %}
    <h1>Add Book</h1>
  <form action="{{ url_for('main.add_book') }}" method="POST">
  {{ form.hidden_tag() }}
      <p>
        {{ form.author.label }}<br>
        {{ form.author() }}
        {% for error in form.author.errors %}
            <span style="color: red;">{{ error }}</span>
        {% endfor %}
      </p>
      <p>
        {{ form.title.label }}<br>
        {{ form.title(size=30) }}
        {% for error in form.title.errors %}
          <span class="error">{{ error }}</span>
        {% endfor %}
      </p>

      <p>
        {{ form.isbn.label }}<br>
        {{ form.isbn() }}
        {% for error in form.isbn.errors %}
          <span class="error">{{ error }}</span>
        {% endfor %}
      </p>

      <p>
        {{ form.publication_year.label }}<br>
        {{ form.publication_year() }}
        {% for error in form.publication_year.errors %}
          <span class="error">{{ error }}</span>
        {% endfor %}
      </p>

      <p>
        {{ form.submit() }}
      </p>
  </form>

  </body>
</html>

app/templates/book_table.html
<table border="1">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Author</th>
                    <th>Publication Year</th>
                    <th>ISBN</th>
                </tr>
            </thead>
            <tbody>
                {% for book, author in results %}
                <tr>
                    <td>{{ book.title }}</td>
                    <td>{{ author.name }}</td>
                    <td>{{ book.publication_year }}</td>
                    <td>{{ book.isbn }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

app/templates/books_sorted.html
 <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <title>Sorted Lists</title>
  </head>
  <body>
  {% include 'navbar.html' %}

  <h1>Books Sorted</h1>
    {% if books %}
        {% include 'book_table.html' %}
    {% else %}
        <p>No books available.</p>
    {% endif %}

  </body>
</html>

app/templates/delete_book.html
 <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <title>Home</title>
  </head>
  <body>
  {% include 'navbar.html' %}

  <h1>Delete Book</h1>


  <form action="{{ url_for('main.delete_book') }}" method="POST">
  {{ form.hidden_tag() }}
      <p>
        {{ form.search.label }}<br>
        {{ form.search() }}
        {% for error in form.search.errors %}
            <span style="color: red;">{{ error }}</span>
        {% endfor %}
      </p>

  <p>
      <p>Are you sure you want to delete the book with the following details?</p>
        {{ form.submit() }}
      </p>
  </form>

  </body>
</html>

app/templates/home.html
 <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <title>Home</title>
  </head>
  <body>
  {% include 'navbar.html' %}

  <h1>Books List</h1>

    {% if results %}
        {% include 'book_table.html' %}
    {% else %}
        <p>No books available.</p>
    {% endif %}
  <h2>Sort Inventory by books or by Authors</h2>
  <form action="{{ url_for('main.index') }}" method="POST">
  {{ form.hidden_tag() }}
      <p>
        {{ form.sorting_criteria.label }}<br>
        {{ form.sorting_criteria() }}
        {% for error in form.sorting_criteria.errors %}
            <span style="color: red;">{{ error }}</span>
        {% endfor %}
      </p>
  <p>
        {{ form.sorting_direction.label }}<br>
        {{ form.sorting_direction() }}
        {% for error in form.sorting_direction.errors %}
            <span style="color: red;">{{ error }}</span>
        {% endfor %}
      </p>

  <p>
        {{ form.submit() }}
      </p>
  </form>

  </body>
</html>

app/templates/navbar.html
<nav>
    <ul>
        <li><a href="{{ url_for("main.index") }}">Home</a></li>
        <li><a href="{{ url_for("main.add_author") }}">Add Author</a></li>
        <li><a href="{{ url_for("main.add_book") }}">Add Book</a></li>
        <li><a href="{{ url_for("main.search") }}">Search Books</a></li>
        <li><a href="{{ url_for("main.delete_book") }}">Delete Book</a></li>
    </ul>
</nav>

app/templates/search.html
 <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <title>Search</title>
  </head>
  <body>
  {% include 'navbar.html' %}

  <h1>Search Inventory</h1>

  <form action="{{ url_for('main.search') }}" method="POST">
  {{ form.hidden_tag() }}
      <p>
        {{ form.item.label }}<br>
        {{ form.item() }}
        {% for error in form.item.errors %}
            <span style="color: red;">{{ error }}</span>
        {% endfor %}
      </p>
  <p>
        {{ form.search.label }}<br>
        {{ form.search() }}
        {% for error in form.search.errors %}
            <span style="color: red;">{{ error }}</span>
        {% endfor %}
      </p>

  <p>
        {{ form.submit() }}
      </p>
  </form>

  <h1>Results</h1>
    {% if results %}
        {% include 'book_table.html' %}
    {% else %}
        <p>No results available.</p>
    {% endif %}



  </body>
</html>